apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hero-manager-marvel
  labels:
    name: hero-manager-marvel
spec:
  selector:
    matchLabels:
      name: hero-manager-marvel
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-marvel
    spec:
      containers:
      - name: hero-manager-marvel
        image: docker.io/library/hero_manager_marvel_image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        resources: {}
        env:
            - name: MARVEL_URl
              value: https://gateway.marvel.com
            - name: MARVEL_PUBLIC_KEY
              value: 10b336182162121bad469acdebead0f5
            - name: MARVEL_PRIVATE_KEY
              value: d1e200bce4a9d602e81d3053e10f8552e5319a4d        
            - name: PORT
              value: "8082"
