apiVersion: v1
kind: Service
metadata:
  name: hero-manager-marvel
  labels:
    name: hero-manager-marvel
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    name: hero-manager-marvel